export const INIT_APP = 'INIT_APP';
export const SHOW_NOTIFCATION = 'SHOW_NOTIFCATION';
export const PUSH_NEW_BREADCRUMB = 'PUSH_NEW_BREADCRUMB';
export const RESET_NEW_BREADCRUMB = 'RESET_NEW_BREADCRUMB';
export const CLEAR_BREADCRUMB = 'CLEAR_BREADCRUMB';

export const TOGGLE_ISSUE_DRAWER = 'TOGGLE_ISSUE_DRAWER';
export const TOGGLE_FEEDBACK_DRAWER = 'TOGGLE_FEEDBACK_DRAWER';
export const TOGGLE_INVITE_DRAWER = 'TOGGLE_INVITE_DRAWER';
