export const PLAN_CREATE_PENDING = 'PLAN_CREATE_PENDING';
export const PLAN_CREATE_FULLFILLED = 'PLAN_CREATE_FULLFILLED';
export const PLAN_LIST_PENDING = 'PLAN_LIST_PENDING';
export const PLAN_LIST_FULLFILLED = 'PLAN_LIST_FULLFILLED';
export const PLAN_LIKE_PENDING = 'PLAN_LIKE_PENDING';
export const PLAN_ADD_FILE_PENDING = 'PLAN_ADD_FILE_PENDING';
export const PLAN_ADD_FILE_FULLFILLED = 'PLAN_ADD_FILE_FULLFILLED';
export const PLAN_DELETE_FILE_PENDING = 'PLAN_DELETE_FILE_PENDING';
export const PLAN_DELETE_FILE_FULLFILLED = 'PLAN_DELETE_FILE_FULLFILLED';

export const PLAN_UPDATE_PENDING = 'PLAN_UPDATE_PENDING';
export const PLAN_UPDATE_FULLFILLED = 'PLAN_UPDATE_FULLFILLED';
