export const PLAN_CREATE_PENDING = 'PLAN_CREATE_PENDING';
export const PLAN_CREATE_FULLFILLED = 'PLAN_CREATE_FULLFILLED';
export const PLAN_LIST_PENDING = 'PLAN_LIST_PENDING';
export const PLAN_LIST_FULLFILLED = 'PLAN_LIST_FULLFILLED';
export const PLAN_ISSUE_LIST_PENDING = 'PLAN_ISSUE_LIST_PENDING';
export const PLAN_ISSUE_LIST_FULLFILLED = 'PLAN_ISSUE_LIST_FULLFILLED';
export const PLAN_LIKE_PENDING = 'PLAN_LIKE_PENDING';
export const PLAN_LIKE_FULLFILLED = 'PLAN_LIKE_FULLFILLED';
