export const REPOSITORY_HISTORY_PENDING = 'REPOSITORY_HISTORY_PENDING';
export const REPOSITORY_HISTORY_FULLFILLED = 'REPOSITORY_HISTORY_FULLFILLED';
export const REPOSITORY_FILES_PENDING = 'REPOSITORY_FILES_PENDING';
export const REPOSITORY_FILES_FULLFILLED = 'REPOSITORY_FILES_FULLFILLED';
export const REPOSITORY_SUMMARY_PENDING = 'REPOSITORY_SUMMARY_PENDING';
export const REPOSITORY_SUMMARY_FULLFILLED = 'REPOSITORY_SUMMARY_FULLFILLED';
export const REPOSITORY_BRANCHES_LIST_PENDING = 'REPOSITORY_BRANCHES_LIST_PENDING';
export const REPOSITORY_BRANCHES_LIST_FULLFILLED = 'REPOSITORY_BRANCHES_LIST_FULLFILLED';
export const REPOSITORY_STATUS_LIST_PENDING = 'REPOSITORY_STATUS_LIST_PENDING';
export const REPOSITORY_STATUS_LIST_FULLFILLED = 'REPOSITORY_STATUS_LIST_FULLFILLED';

export const REPOSITORY_READ_FILE_PENDING = 'REPOSITORY_READ_FILE_PENDING';
export const REPOSITORY_READ_FILE_FULLFILLED = 'REPOSITORY_READ_FILE_FULLFILLED';
export const REPOSITORY_WRITE_FILE_PENDING = 'REPOSITORY_WRITE_FILE_PENDING';
export const REPOSITORY_WRITE_FILE_FULLFILLED = 'REPOSITORY_WRITE_FILE_FULLFILLED';

export const REPOSITORY_COMMIT_PENDING = 'REPOSITORY_COMMIT_PENDING';
export const CREATE_BRANCH = 'CREATE_BRANCH';