export const REPOSITORY_HISTORY_PENDING = 'REPOSITORY_HISTORY_PENDING';
export const REPOSITORY_HISTORY_FULLFILLED = 'REPOSITORY_HISTORY_FULLFILLED';
export const REPOSITORY_FILES_PENDING = 'REPOSITORY_FILES_PENDING';
export const REPOSITORY_FILES_FULLFILLED = 'REPOSITORY_FILES_FULLFILLED';
