export const USER_FETCH_PENDING = 'USER_FETCH_PENDING';
export const USER_FETCH_FULLFILLED = 'USER_FETCH_FULLFILLED';
export const USER_UPDATE_PENDING = 'USER_UPDATE_PENDING';
export const SEND_FEEDBACK = 'SEND_FEEDBACK';
export const USER_ACTIVITY_PENDING = 'USER_ACTIVITY_PENDING';
export const USER_ACTIVITY_FULLFILLED = 'USER_ACTIVITY_FULLFILLED';